import operator
from typing import Annotated, TypedDict, List, Dict, Any, Optional, Union

class AgentState(TypedDict):
    """
        The shared state of the MoE MemoryGraph agent.
        
        This TypedDict defines the data schema that flows through every node 
        in the LangGraph orchestration. It handles input context, expert routing, 
        and the parallel accumulation of results.
        """   
    # --- Input Context (Immutable) ---
    # The raw query from the user
    query: str
    # Critical for enterprise isolation (e.g., "acme_corp")
    tenant_id: str
    # Used for Short-Term Memory (STM) lookup
    session_id: str
    
    # --- Memory Previews (Gate Inputs) ---
    # Metadata returned by the 'load_preview' node to help the Gate decide.
    # We use Optional because these might be None before the preview node runs.
    semantic_preview: Optional[Dict[str, Any]]
    vector_preview: Optional[Dict[str, Any]]
    ltm_preview: Optional[Dict[str, Any]]
    
    # --- MoE Routing Decisions ---
    # The list of expert names (e.g., ["SemanticQuery", "Compliance"]) selected by the Gate
    selected_experts: List[str]
    # The reasoning behind the selection (explains why the AI chose those experts.)
    gate_rationale: Optional[str]
    # Confidence scores for the gate's decision
    gate_confidence: float
    
    # --- Result Accumulator (Crucial for Parallelism) ---
    # This is the most critical field for MoE.
    # Annotated[list, operator.add] tells LangGraph: "When multiple experts return 
    # data simultaneously, ADD their results to this list; do not overwrite each other."
    expert_results: Annotated[List[Dict[str, Any]], operator.add]
    
    # --- Final Output ---
    # The structured answer generated by the 'synthesize' node
    final_answer: Optional[Dict[str, Any]]
    # The final confidence score of the answer
    answer_confidence: float